### PR TITLE
Copyright infringement and associated map

### PR DESCRIPTION
**Pull request by Fabrice-TIERCELIN**
Hi @misiokles,

This PR rescores the mod as it was a copyright infringement of [Yasuharu Takanasha's Kanashige](https://www.youtube.com/watch?v=ZweLDhbs7r0). It also adds a map featuring the mod.

- AI for the music: Udio
- Prompt for the music: `emotional, romantism, strings, instrumental, Cinematic classical`
- AI for the soundscape: [_Tango2_](https://huggingface.co/spaces/fantos/tango2)
- Prompt for the soundscape: `Mountain, winter, wind, soundscape`
- Prompt for the description & prolog: `Write me two texts that describ a world for a scenario of a 4X strategy video game that takes place in a medieval fantasy universe with might and magic where mythological creatures live. The first text is a general presentation of the scenario and the second text is a description of how things come to the current situation. The scenario takes place in country, desert, snow, sea and so on. There are 5 factions that will fight and only one will win. You must not break the fourth wall. Only use paragraph, not list. Do not repeat this given context as everybody already knows that, gives more details.`

### CODE REVIEW

**Comment by misiokles** [comment]
Please add this theme as second track to this terrain
`"music" : [ "asphalt/Kanashige", "asphalt/Whispers_of_the_Heart" ],`

**Comment by Fabrice-TIERCELIN** [comment]
_Second track_? I didn't know that. How it works? The user will have an option in the interface to switch?

**Comment by Fabrice-TIERCELIN** [comment]
✔️DONE

I have fixed it because you asked me to do so. Now there is no point to do so because the reason I have created a new music is not because the former one is bad but because it's illegal.

At least, we have a new map.

**Comment by misiokles** [comment]
Not working map (needs additional 2-way portals mod to work), but yes., we have a map.

**Comment by Fabrice-TIERCELIN** [comment]
I have successfully tested the map with only the Asphalt mod

**Comment by krs0** [comment]
So Kanashige is gone? Was one of the reasons I loved Forge :(.

**Comment by Fabrice-TIERCELIN** [comment]
Finally not

**Comment by krs0** [comment]
? is deleted from mod...

**Comment by Fabrice-TIERCELIN** [comment]
The new theme has only been added in the source. The original theme is still the theme of the mod.

**Comment by krs0** [comment]
Hmmmm... Am I missing something? This was commit contents.

image

**Comment by Fabrice-TIERCELIN** [comment]
The two files are in the folder:

https://github.com/vcmi-mods/asphalt-terrain/tree/vcmi-1.6/asphalt-terrain/content/music/asphalt

I think @misiokles has readded the file because the PR has removed it.

**Pull request merged**
